
image: node:14-buster

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules


before_script:
  - yarn config set cache-folder .yarn
  - yarn install

tests:
  stage: test
  script:
    - make test

typescript:
  stage: test
  script:
    - yarn run tsc --noEmit

lint:
  stage: test
  script:
    - yarn run lint

ui-chrome:
  variables:
    CYPRESS_DASHBOARD_KEY: "$CYPRESS_DASHBOARD_KEY"
  image: cypress/browsers:node16.5.0-chrome94-ff93
  stage: test
  script:
    - make build
    # run the server in the background
    - yarn serve -s build &
    # run Cypress tests
    - npx cypress run --browser chrome --record --key $CYPRESS_DASHBOARD_KEY

pages:
  stage: deploy
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
    - apt-get update -qq && apt-get install -y hugo python3 python3-toml python3-yaml
  script:
    - make -C website build  # Build landing page into website/public/.
    - make apply-beta-basename  # Overwrite settings so the Router works in deployment.
    - make build  # Build beta application into build/.
    - rm -rf public/  # Remove the folder with the same name.
    - mv website/public public  # Put the landing site in place.
    - mv build public/releases/beta  # Put the beta application in place.
  artifacts:
    paths:
      - public
  only:
    - main
