openapi: 3.0.3
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/theonlyway/Openlifter/1.0.0
info:
  description: API designed to expose data from Openlifter
  version: "1.0.0"
  title: Openlifter API
  contact:
    url: https://github.com/theonlyway/openlifter
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Lifters
    description: Lifter information
  - name: Lights
    description: API for lifting lights
  - name: Health
    description: API health check
paths:
  /lifter/{platform}/order:
    post:
      tags:
        - Lifters
      summary: Update the lifter order
      description: |
        Update the current lifter
      parameters:
        - name: platform
          in: path
          description: Platform number
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LifterOrder"
      responses:
        '200':
          description: Order update response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '503':
          description: Order update response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
      security:
        - api_key: []
  /lifter/{platform}/current:
    get:
      tags:
        - Lifters
      summary: Returns the current lifter
      description: |
        Returns the current lifter
      parameters:
        - name: platform
          in: path
          description: id of the account to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Current lifter data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnyValue'
      security:
        - api_key: []
  /lifter/{platform}/next:
    get:
      tags:
        - Lifters
      summary: Returns the next lifter
      description: |
        Returns the current lifter
      parameters:
        - name: platform
          in: path
          description: id of the account to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Next lifer data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnyValue'
      security:
        - api_key: []
  /lights/{platform}:
    get:
      tags:
        - Lights
      summary: Returns the code used for the lights
      description: |
        Returns the health of the API
      parameters:
        - name: platform
          in: path
          description: id of the account to return
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lights code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnyValue'
      security:
        - api_key: []
  /health:
    get:
      tags:
        - Health
      summary: Checks the health of the API
      description: |
        Returns the health of the API
      responses:
        '200':
          description: API health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiHealth'
      security:
        - api_key: []
components:
  schemas:
    LifterOrder:
      type: object
      properties:
        orderedEntries:
            type: array
            items:
              type: object
        attemptOneIndexed:
          type: integer
        currentEntryId:
          nullable: true
          type: integer
        nextAttemptOneIndexed:
          type: integer
          nullable: true
          example: null
        nextEntryId:
          type: integer
          nullable: true
          example: null
    ApiHealth:
      type: object
      required:
        - apiStatus
        - databaseStatus
      properties:
        apiStatus:
          type: string
        databaseStatus:
          type: string
        failureMessage:
          type: string
    OrderResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    AnyValue: {}
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
