openapi: 3.0.3
info:
  title: Openlifter API
  description: API designed to expose data from Openlifter
  contact:
    url: https://github.com/theonlyway/openlifter
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/theonlyway/Openlifter/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: lifters
  description: Lifter information
- name: registrations
  description: Lifter information
- name: health
  description: API health check
paths:
  /lifter/{platform}/order:
    post:
      tags:
      - lifters
      summary: Update the lifter order
      description: |
        Update the current lifter
      operationId: lifter_platform_order_post
      parameters:
      - name: platform
        in: path
        description: id of the account to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentLifter'
      responses:
        "200":
          description: current lifter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLifter'
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.lifters_controller
  /registrations:
    put:
      tags:
      - registrations
      summary: Returns the current lifter
      description: |
        Returns the current lifter
      operationId: registrations_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnyValue'
      responses:
        "200":
          description: current lifter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLifter'
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.registrations_controller
  /lifter/{platform}/current:
    get:
      tags:
      - lifters
      summary: Returns the current lifter
      description: |
        Returns the current lifter
      operationId: lifter_platform_current_get
      parameters:
      - name: platform
        in: path
        description: id of the account to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: current lifter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLifter'
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.lifters_controller
  /lifter/{platform}/next:
    get:
      tags:
      - lifters
      summary: Returns the next lifter
      description: |
        Returns the current lifter
      operationId: lifter_platform_next_get
      parameters:
      - name: platform
        in: path
        description: id of the account to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: next lifter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentLifter'
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.lifters_controller
  /health:
    get:
      tags:
      - health
      summary: Checks the health of the API
      description: |
        Returns the health of the API
      operationId: health_get
      responses:
        "200":
          description: API health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiHealth'
      security:
      - api_key: []
      x-openapi-router-controller: swagger_server.controllers.health_controller
components:
  schemas:
    CurrentLifter:
      type: object
      properties:
        orderedEntries:
          type: array
          items:
            type: object
        attemptOneIndexed:
          type: number
        currentEntryId:
          type: number
        nextAttemptOneIndexed:
          type: number
          nullable: true
        nextEntryId:
          type: number
          nullable: true
      example:
        attemptOneIndexed: 0.80082819046101150206595775671303272247314453125
        orderedEntries:
        - {}
        - {}
        currentEntryId: 6.02745618307040320615897144307382404804229736328125
        nextEntryId: 5.962133916683182377482808078639209270477294921875
        nextAttemptOneIndexed: 1.46581298050294517310021547018550336360931396484375
    ApiHealth:
      required:
      - apiStatus
      - databaseStatus
      type: object
      properties:
        apiStatus:
          type: string
        databaseStatus:
          type: string
        failureMessage:
          type: string
      example:
        databaseStatus: databaseStatus
        failureMessage: failureMessage
        apiStatus: apiStatus
    AnyValue: {}
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
      x-apikeyInfoFunc: swagger_server.controllers.authorization_controller.check_api_key

