# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApiHealth(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, database_status: str=None):  # noqa: E501
        """ApiHealth - a model defined in Swagger

        :param status: The status of this ApiHealth.  # noqa: E501
        :type status: str
        :param database_status: The database_status of this ApiHealth.  # noqa: E501
        :type database_status: str
        """
        self.swagger_types = {
            'status': str,
            'database_status': str
        }

        self.attribute_map = {
            'status': 'status',
            'database_status': 'databaseStatus'
        }
        self._status = status
        self._database_status = database_status

    @classmethod
    def from_dict(cls, dikt) -> 'ApiHealth':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiHealth of this ApiHealth.  # noqa: E501
        :rtype: ApiHealth
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this ApiHealth.


        :return: The status of this ApiHealth.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ApiHealth.


        :param status: The status of this ApiHealth.
        :type status: str
        """

        self._status = status

    @property
    def database_status(self) -> str:
        """Gets the database_status of this ApiHealth.


        :return: The database_status of this ApiHealth.
        :rtype: str
        """
        return self._database_status

    @database_status.setter
    def database_status(self, database_status: str):
        """Sets the database_status of this ApiHealth.


        :param database_status: The database_status of this ApiHealth.
        :type database_status: str
        """

        self._database_status = database_status
